# this is first makefile to do here

#simple compile

CC=g++
OPTS=-pg -ggdb
LIBS=-lopengl32 -lglu32 -Llib -lglut32

compile:
	$(CC) $(OPTS) main.cpp 3dmodel/source/*.cpp -o Debug/3DGameEngine.exe $(LIBS)
